version: '3.3'
services:
  api:
    build:
      context: ./news_api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./envs/api.env
      - ./envs/db.env
    expose:
      - 8000
    volumes:
      - ./volumes/api/static:/usr/src/app/static
      - ./volumes/api/logs:/usr/src/app/logs

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql/data/
    env_file:
      - ./envs/db.env

  nginx:
    restart: always
    build: ./nginx
    ports:
    - 80:80
    volumes:
      - ./volumes/api/static:/usr/src/app/static
    depends_on:
      - api